name: Unit test coverage

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Set current date
        run: echo "VERSION_TIMESTAMP=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - uses: pnpm/action-setup@v4
        with:
          version: 9.14.4

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm test:unit:coverage

      - run:
          echo "PATHS=$(find ./packages -type f -path '*/**/coverage/lcov.info' |  paste -sd ',' -)" >>
          $GITHUB_OUTPUT
        id: coverage-reports

      - uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ steps.coverage-reports.outputs.PATHS}}

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_LCOV_REPORTPATHS: ${{ steps.coverage-reports.outputs.PATHS}}
